# Generated by Django 5.1.3 on 2025-04-10 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('CourseID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('TopInstructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_instructor_courses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('SectionID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('AssignmentID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('DueDate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('SectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('VideoID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=255)),
                ('Description', models.TextField()),
                ('URL', models.URLField()),
                ('Duration', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('SectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.coursesection')),
            ],
        ),
        migrations.CreateModel(
            name='VideoQA',
            fields=[
                ('QAID', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.TextField()),
                ('Answer', models.TextField(blank=True, null=True)),
                ('Timestamp', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_questions', to=settings.AUTH_USER_MODEL)),
                ('VideoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_entries', to='courses.video')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubmissionDate', models.DateTimeField(blank=True, null=True)),
                ('Grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('Status', models.CharField(default='Not Started', max_length=20)),
                ('Feedback', models.TextField(blank=True, null=True)),
                ('AssignmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_submissions', to='courses.assignment')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('StudentID', 'AssignmentID')},
            },
        ),
        migrations.CreateModel(
            name='InstructorCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AssignmentDate', models.DateTimeField(auto_now_add=True)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='courses.course')),
                ('InstructorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('InstructorID', 'CourseID')},
            },
        ),
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnrollmentDate', models.DateTimeField(auto_now_add=True)),
                ('CourseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='courses.course')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('StudentID', 'CourseID')},
            },
        ),
        migrations.CreateModel(
            name='VideoStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastWatched', models.DateTimeField(auto_now=True)),
                ('Progress', models.IntegerField(default=0)),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_videos', to=settings.AUTH_USER_MODEL)),
                ('VideoID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_views', to='courses.video')),
            ],
            options={
                'unique_together': {('StudentID', 'VideoID')},
            },
        ),
    ]
